### ISSUE TITLE
How to use this effectively for Indian Markets NSE Stocks

### ISSUE THREAD

**Issue by rahulmr** [ooples/OoplesFinance.YahooFinanceAPI#78]
Thanks for the wonderful work.
Could you please provide some information on how we can use this to work with Indian Markets NSE Stocks?

The symbols are different for NSE India.
I also wanted to understand if there is any country specific methods to get the information like breakout stocks, etc.

**Comment by ooples** [comment]
There are a few API calls in this library that take a Country as a parameter such as the one below:

`await GetTopTrendingStocksAsync(Country.India, 10);`

The above code can be used to get the top 10 trending Indian stocks using NSE India and there are quite a few methods that can use the Country but I see that I need to make it more uniform across the board because to properly utilize the country code, you need to initialize the yahoo client class by using this code:

var yahooClient = new YahooClient(Country.India);
var keyStats = await GetKeyStatisticsAsync("NIFTY");

Overall for now I would experiment with this library but make sure to initialize YahooClient with the country of your choice

**Comment by rahulmr** [comment]
Thanks!
