### ISSUE TITLE
Some endpoints not working anymore

### ISSUE THREAD

**Issue by andrew-baylis** [ooples/OoplesFinance.YahooFinanceAPI#97]
Unfortunately, some of the end points are no longer working returning an "Unauthorised" error instead:
Key ones for me are the Historical data, Dividend data and Splits data.
I also tried a rebuiild of your 1.6.9 and ran all the Unit tests. 94 of them failed.

**Comment by andrew-baylis** [comment]
Update - I found that editing the BuildYahooCsvUrl method of UrlHelper to REMOVE the &events property of the url produced the required data for dividends, splits and history.  With that tweak, the only method not working is the GetInsights which I can manage without!

**Comment by andrew-baylis** [comment]
Hmmm... the update no longer gives dividens etc. Reverting to the original now seems to work without causing ther original error. Something is up with the api endpoints :(

**Comment by ooples** [comment]
@andrew-baylis I'm looking into these current issues so any additional info you could provide would be greatly appreciated. I will let you know if I have any updates

**Comment by ooples** [comment]
I had a strange issue with version 1.6.9 and I have tested it and resolved it with 1.6.10 so please get that version and confirm if this works for you

**Comment by ooples** [comment]
That is odd since it's compiling correctly for me and these changes were part of the new version

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by andrew-baylis** [comment]
Update - I have tracked down the test fail issue to the build target frameworks - when the target framework is set to just net8.0, only three tests fail. When TargetFrameworks is set to 
```
<TargetFrameworks>net8.0;net7.0;net6.0;net48</TargetFrameworks>
```
94 tests fail
I suspect it is to do with the version of c# that is used by "latest" in the language version for the range of TargetFrameworks whereas when just using net8.0, the latest is c# 12 whereas net6.0 uses c# 10. Otherwise, your csproj file doesn't seem to have version specific features (I haven't checked your code base for #if statements, though)

**Comment by ooples** [comment]
@andrew-baylis I'm not sure what happened but I see that the master branch doesn't have the latest changes after doing the latest merge from the dev branch so not sure what caused that but I just did a commit that should fix that issue. Also the reason for the unit tests failing is due to the API calls not being properly mocked and so we are executing actual API calls when running the unit tests and Yahoo Finance rate limits us. I have a fix I'm working on for this but it will take an entire redesign of the library due to how I have it currently designed. I will look into offering some overload methods to have a user specify multiple event types and I plan on doing this for version 1.7 along with the unit test fixes. Feel free to submit pull requests in the meantime.
